 package com.crmindz.service;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Random;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.crmindz.dao.TicketManagementDaoImpl;
import com.crmindz.model.Login;
import com.crmindz.model.Ticket;
import com.crmindz.model.User;

/**
 * @author SivaramaKrishnaLinga
 *
 */
@Service
public class TicketManagementService {
	@Autowired
	TicketManagementDaoImpl ticketManagementDaoImpl;

	/** This method validate the email entered by the user.
	 * @param user
	 * @return
	 */
	public boolean validateRegistration(User user) {
		List<Login> listOfEmails = ticketManagementDaoImpl.retrieveEmail(user);
		if (listOfEmails.isEmpty())
			return true;
		else
			return false;
	}

	/**This method submit the registration data to the register method in DAO class
	 * @param user
	 * @return
	 */
	public boolean register(User user) {
		if (ticketManagementDaoImpl.register(user))
			return true;
		else
			return false;
	}

	/**This method validate login credentials
	 * @param login
	 * @return
	 */
	public List<Login> validateLogin(Login login) {
		List<Login> loginDetailsFromDb = ticketManagementDaoImpl.getLoginDetails(login);
		return loginDetailsFromDb;
	}

	/**This method returns tickets created by the User from DAO to the COntroller class.
	 * @param ticket
	 * @return
	 */
	public List<Ticket> displayTicketsByID(Ticket ticket) {
		List<Ticket> listOfTickets = ticketManagementDaoImpl.displayTicketData(ticket);
		return listOfTickets;
	}

	/**This method send created ticket information from the Controller to the DAO.
	 * @param ticket
	 * @return
	 */
	public boolean addTicket(Ticket ticket) {
		if (ticketManagementDaoImpl.addTicket(ticket)) {
			return true;
		} else
			return false;
	}

	/**This method sends pending tickets data from DAO to the controller.
	 * @return
	 */
	public List<Ticket> displayPending() {
		List<Ticket> pendingTickets = new ArrayList<Ticket>();
		List<Ticket> listOfTickets = ticketManagementDaoImpl.displayAll();
		for (Ticket ticket : listOfTickets) {
			if ("pending".equals(ticket.getTstatus())) {
				pendingTickets.add(ticket);
			}
		}
		return pendingTickets;
	}

	/**This method get the approved Tickets Data from the DAO class and send it to the controller.
	 * @return List of approved Tickets to the Controller
	 */
	public List<Ticket> displayApproved() {
		List<Ticket> pendingTickets = new ArrayList<Ticket>();
		List<Ticket> listOfTickets = ticketManagementDaoImpl.displayAll();
		for (Ticket ticket : listOfTickets) {
			if ("approved".equals(ticket.getTstatus())) {
				pendingTickets.add(ticket);
			}
		}
		return pendingTickets;
	}

	/**This method get the rejected Tickets Data from the DAO class and send it to the controller.
	 * @return List of rejected Tickets to the Controller.
	 */
	public List<Ticket> displayRejected() {
		List<Ticket> pendingTickets = new ArrayList<Ticket>();
		List<Ticket> listOfTickets = ticketManagementDaoImpl.displayAll();
		for (Ticket ticket : listOfTickets) {
			if ("rejected".equals(ticket.getTstatus())) {
				pendingTickets.add(ticket);
			}
		}
		return pendingTickets;
	}

	/**This method takes the approved tickets request from the controller and pass it to the DAO class.
	 * It send the Appropriate boolean response generated by the DAO class method to the Controller.
	 * @param ticket
	 * @return
	 */
	public boolean approveTicket(Ticket ticket) {
		if (ticketManagementDaoImpl.processTicket(ticket)) {
			return true;
		} else {
			return false;
		}
	}

	/**This method takes the rejected tickets request from the controller and pass it to the DAO class.
	 * It send the Appropriate boolean response generated by the DAO class method to the Controller.
	 * @param ticket
	 * @return
	 */
	public boolean rejectTicket(Ticket ticket) {
		if (ticketManagementDaoImpl.processTicket(ticket)) {
			return true;
		} else {
			return false;
		}
	}

	/**This method generate random 10 digit alpha numeric number.
	 * @return
	 */
	public String generateTicketNumber() {
		String SALTCHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
		StringBuilder salt = new StringBuilder();
		Random rnd = new Random();
		while (salt.length() < 10) { // length of the random string.
			int index = (int) (rnd.nextFloat() * SALTCHARS.length());
			salt.append(SALTCHARS.charAt(index));
		}
		String saltStr = salt.toString();
		return saltStr;
	}

	/**This method append all the states data from the DAO to the variable state and send it to the controller method.
	 * @return
	 */
	public String getStates() {
		String states = "";
		List<Map<String, Object>> listOfStates = ticketManagementDaoImpl.getStates();
		for (Map<String, Object> map : listOfStates) {
			for (Map.Entry<String, Object> entry : map.entrySet())
				states += "<option value='" + entry.getValue() + "'>" + entry.getValue() + "</option>";
		}
		return states;
	}

	/** This method method append all the categories data returned from DAO to the variable categoryData and send it to the controller.
	 * @return
	 */
	public String getCategories() {
		String categoryData = "";
		List<Map<String, Object>> categories = ticketManagementDaoImpl.getCategoriesList();
		for (Map<String, Object> map : categories) {
			for (Map.Entry<String, Object> entry : map.entrySet())
				categoryData += "<option value='" + entry.getValue() + "'>" + entry.getValue() + "</option>";
		}
		return categoryData;
	}

	/**This method append all the subcategory data acquired from DAO to the variable subCategoryData and return that variable to the controller.
	 * @param categoryValue
	 * @return
	 */
	public String getSubCategories(String categoryValue) {
		String subCategoryData = "";
		List<Map<String, Object>> SubCategories = ticketManagementDaoImpl.getSubCategoriesList(categoryValue);
		for (Map<String, Object> map : SubCategories) {
			for (Map.Entry<String, Object> entry : map.entrySet())
				subCategoryData += "<option value='" + entry.getValue() + "'>" + entry.getValue() + "</option>";
		}
		return subCategoryData;
	}

}
